#!/bin/sh

set -e

case "$1" in
    configure|triggered)
    
        if [ -x /usr/bin/gtk-update-icon-cache ]; then
            gtk-update-icon-cache -f -t /usr/share/icons/hicolor || true
        fi

        nemo -q || true
                
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0


